backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Mode of Action", name: "modeofaction", widget: "text" }